### ISSUE TITLE
ARGB option doesn't work as expected

### ISSUE THREAD

**Issue by takuhii** [igorkulman/ChangeMenuBarColor#48]
When I use the new ARGB it does a transparent rectangle, but I can't see the original image underneath it...
<img width="1057" alt="Screenshot 2021-02-07 at 16 19 59" src="https://user-images.githubusercontent.com/193907/107152534-6360d780-6960-11eb-9786-09c4610b37b7.png">

Is that intentional? or am I over-thinking it?

**Comment by igorkulman** [comment]
Looks like the sanme problem as describe in https://github.com/igorkulman/ChangeMenuBarColor/issues/35#issuecomment-760902260.

The wallpaper image is generated correctly, you can verify by checking it in `~/Library/Application Support/ChangeMenuBarColor` (the specific path for the generated wallpaper image is printed to the console). 

The problem is that macOS picks something like a "dominant" color and uses it for the whole menu bar area.

**Comment by takuhii** [comment]
Sounds like the Menu bar isn't truly transparent then?

**Comment by igorkulman** [comment]
> Sounds like the Menu bar isn't truly transparent then?
> […](#)

Not really. Looks like it takes the color right "under" it in the wallpaper with some adjustments. But all of this is just a guess as it is  completely undocumented part of mac OS.
